function impossible_pairs = getImpossiblePairs(varargin)

%returns a struct where each dorsal cortical region is associated with a
%list of other regions that are impossible to target simultaneously

%TODO compute pairs based on minimum distance between them using Allen CCF
%TODO deal with fields not being allowed to have a dash...

impossible_pairs = struct(...
'VISp',strings(0),...
'VISpm',strings(0),...
'VISam',strings(0),...
'VISa',strings(0),...
'VISrl',strings(0),...
'VISal',strings(0),...
'VISl',"MOs",...
'RSPd',["AUDd" "AUDpo" "AUDp" "TEa" "SSp-m" "VISpl" "VISpor"],...
'RSPagl',"AUDp",...
'SSpbfd',strings(0),...
'SSptr',strings(0),...
'SSpul',["VISpl" "VISpor"],...
'SSpun',["VISpl" "VISpor"],...
'SSpll',["VISpl" "VISpor"],...
'SSpn',["VISpl" "VISpor"],...
'SSs',strings(0),...
'AUDd',["RSPd" "MOs" "MOp"],...
'MOp',["AUDd" "VISpl" "VISpor" "TEa" "AUDpo" "AUDp"],...
'SSpm',["RSPd" "VISpl" "VISpor" "TEa"],...
'AUDpo',["MOs" "RSPd" "MOp"],...
'AUDp',["MOs" "RSPd" "MOp" "RSPagl"],...
'TEa',["MOs" "RSPd" "MOp" "SSp-m"],...
'MOs',["AUDd" "AUDp" "AUDpo" "VISpl" "VISpor" "TEa" "VISli" "VISl"],...
'VISli',"MOs",...
'VISpl',["MOs" "MOp" "SSp-m" "RSPd" "SSp-ul" "SSp-un" "SSp-n" "SSp-ll"],...
'VISpor',["MOs" "MOp" "SSp-m" "RSPd" "SSp-ul" "SSp-un" "SSp-n" "SSp-ll"]);