
saveflag = true;
overwrite = true;

%% loading


% load sPaths from canonical sessions
%load("canonicalSessions.mat");

%subjLearners = {'SP035','SP037','SP044','SP046','SP054','SP058','SP060','SP061','SP063','SP066','SP067','SP072','SP075','SP076'};
%subjZebraNoise = {'SP061','SP063','SP066','SP067','SP072','SP075','SP076'};

sPaths = IBL_listSessionPaths('root','Y:\Subjects\SP081',...
    'protocol',{'trainingChoiceWorld','biasedChoiceWorld'},'mpci',true,...
    'fullContrastSet',true,'trials',400);

% sPaths = IBL_listSessionPaths('root','Y:\Subjects\',...
%     'protocol',{'trainingChoiceWorld','biasedChoiceWorld'},'mpci',true,...
%    'fullContrastSet',true,'trials',400);

% sPaths = IBL_listSessionPaths('root','Y:\Subjects\',...
%     'protocol',{'trainingChoiceWorld','biasedChoiceWorld'},'mpci',true...
%     );

% sPaths = IBL_listSessionPaths('root','Y:\Subjects\',...
%     'protocol',{'trainingChoiceWorld','biasedChoiceWorld','cuedBiasedChoiceWorld'},'mpci',true...
%     );

% sPaths = IBL_listSessionPaths('root','Y:\Subjects\',...
%      'protocol',{'trainingChoiceWorld','biasedChoiceWorld'},'mpci',true,...
%      'fullContrastSet',true);

%sPaths = filter_session_paths_by_subject(sPaths,subjLearners);
%sPaths = filter_session_paths_by_subject(sPaths,subjZebraNoise);


%% parameters

params_stimSide100 = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'contrastDiff', ...
    'trialTypeVals',   [-1,-.5,-.25,-.125,-.0625,0,.0625,.125,.25,.5,1], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'stimOn'}, ...
    'twin_all',        [-1,3], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5],[0.5,0.7]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           1, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_stimSide = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'contrastDiff', ...
    'trialTypeVals',   [-1,-.5,-.25,-.125,-.0625,0,.0625,.125,.25,.5,1], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'stimOn'}, ...
    'twin_all',        [-1,3], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5],[0.5,0.7]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           5, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_stimSide100_goCue = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'contrastDiff', ...
    'trialTypeVals',   [-1,-.5,-.25,-.125,-.0625,0,.0625,.125,.25,.5,1], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'goCue'}, ...
    'twin_all',        [-1,3], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5],[0.5,0.7]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           1, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_stimSide_goCue = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'contrastDiff', ...
    'trialTypeVals',   [-1,-.5,-.25,-.125,-.0625,0,.0625,.125,.25,.5,1], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'goCue'}, ...
    'twin_all',        [-1,3], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5],[0.5,0.7]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           5, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_choice = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'choice', ...
    'trialTypeVals',   [-1,1], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'choiceMovement'}, ...
    'twin_all',        [-2.5,1.5], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5],[0.5,0.7]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           1, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_feedback = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'feedbackType', ...
    'trialTypeVals',   [-1,1], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'feedback'}, ...
    'twin_all',        [-1.5,2.5], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5],[0.5,0.7]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           1, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_block = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'probabilityLeft', ...
    'trialTypeVals',   [.2,.8], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'stimOn'}, ...
    'twin_all',        [-2,2], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.5,-0.3],[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           1, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_block_goCue = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'probabilityLeft', ...
    'trialTypeVals',   [.2,.8], ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'goCue'}, ...
    'twin_all',        [-2,2], ...
    'twin_bl',         'none', ...
    'twin_ev',         {[-0.5,-0.3],[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5]}, ...
    'stat_to_use',     {'ccMeanDiff'}, ...
    'nComp',           1, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

params_mov = struct( ...
    'activity_type',   'deconv', ...
    'trialTypeField',  'movement', ...
    'trialTypeVals',   '', ...
    'trialTypeFilter', '', ...
    'condFields',      {''}, ...
    'evnt',            {'firstMovement'}, ...
    'twin_all',        [-1,3], ...
    'twin_bl',         [-0.6,-0.4], ...
    'twin_ev',         {[-0.3,-0.1],[-0.1,0.1],[0.1,0.3],[0.3,0.5],[0.5,0.7]}, ...
    'stat_to_use',     {'ccMean'}, ...
    'nComp',           nan, ...
    'nTrialsMin',      20, ...
    'nTrialsToKeep',   false, ...
    'minTrialsPerCond',10, ...
    'cv',              '', ...
    'pthresh',         0.05, ...
    'nPseudoSessions', 199 ...
    );

%params_all = [params_stimSide100, params_stimSide, params_choice, params_feedback, params_block];
params_all = [params_stimSide100_goCue, params_stimSide_goCue,  params_choice, params_feedback, params_block_goCue];
%params_all = [params_stimSide, params_choice, params_feedback, params_mov];
%params_all = params_stimSide;
%params_all = params_mov;

%% loop over paths
for i=1:length(sPaths)
    fprintf('\nSession %d/%d',i,length(sPaths))
    try 
        get_taskTunedROIs(sPaths{i},params_all,'overwriteExisting', overwrite, 'saveToFOV',saveflag); 
        %get_passiveMovieCorrROIs(sPaths{i},'overwriteExisting', true, 'makePlots', false);
        %get_passiveTunedROIs(sPaths{i},'saveToFOV',saveflag,'overwriteExisting',true);
    catch 
        fprintf('error, skipped.\n'); 
    end
end

%% now you can produce the summary maps
%IBL_densityMaps_batch