function summary = plotFeatureSelectiveByRegion( ...
    sessionPaths, predictorNames, options)
%PLOTFEATURESELECTIVEBYREGION Aggregate sessions by Allen region.
%
% Runs getSessionFractionSelectiveByRegion for each supplied session,
% aligns Allen regions across sessions, and calculates the unweighted mean
% and standard deviation of the session-level selective fractions.
%
% One subplot is produced for each Allen region. Each subplot contains one
% bar per predictor, with error bars showing the standard deviation across
% sessions.
%
% INPUTS
% ------
% sessionPaths
%   String vector containing session folders.
%
% predictorNames
%   Optional predictor names. If empty, predictor names are inferred from
%   the first session and then required for the remaining sessions.
%
% OPTIONS
% -------
% minimumDE
%   Optional full-model deviance filter in percent.
%
% fullThresholdPercent
%   Selectivity threshold for deFull, in percent. Default: 2.
%
% uniqueThresholdPercent
%   Selectivity threshold for deUnique, in percent. Default: 1.
%
% roiTypeValue
%   ROI type interpreted as a cell. Default: 1.
%
% validRegionIds
%   Optional region IDs to include.
%
% minimumCellsPerRegion
%   Minimum number of valid cells required within a session-region-
%   predictor combination. Fractions based on fewer cells are set to NaN.
%   Default: 1.
%
% minimumSessionsPerRegion
%   Minimum number of sessions required to plot a region. Default: 1.
%
% sharedYLimits
%   Use common y-limits across region tiles. Default: true.
%
% showIndividualSessions
%   Overlay session-level fractions as points. Default: false.
%
% figurePosition
%   Figure position. Default: [100 100 1000 800].
%
% OUTPUT
% ------
% summary.fractionBySession
%   S-by-R-by-P session-level fractions.
%
% summary.meanFraction
%   R-by-P mean across sessions.
%
% summary.semFraction
%   R-by-P standard deviation across sessions.
%
% summary.nSessions
%   R-by-P number of contributing sessions.
%
% summary.table
%   Long-form summary table.

arguments
    sessionPaths (:,1) string
    predictorNames (1,:) string = strings(1,0)

    options.minimumDE double = 2
    options.fullThresholdPercent (1,1) double = 2
    options.uniqueThresholdPercent (1,1) double = 2
    options.roiTypeValue (1,1) double = 1
    options.validRegionIds (:,1) double = zeros(0,1)

    options.stPath (1,1) string = ...
        "C:\Users\Samuel\Documents\GitHub\allenCCF\structure_tree_safe_2017.csv"

    options.CCFdir (1,1) string = ...
        "C:\Users\Samuel\Documents\GitHub\allenCCF"

    options.regionColorMode (1,1) string ...
        {mustBeMember(options.regionColorMode, ...
        ["ccf","standard"])} = "ccf"

    options.minimumCellsPerRegion (1,1) double ...
        {mustBeInteger,mustBePositive} = 100

    options.minimumSessionsPerRegion (1,1) double ...
        {mustBeInteger,mustBePositive} = 1

    options.sharedLimits (1,1) logical = true
    options.showIndividualSessions (1,1) logical = true

    options.figurePosition (1,4) double = ...
        [100 0 900 400]

    options.plotFractionAboveUniqueThreshold (1,1) logical = false

    options.uniqueFractionThresholdPercent (1,1) double = 1

    options.sessionMarkerSize (1,1) double ...
        {mustBePositive} = 8

    options.sessionMarkerAlpha (1,1) double ...
        {mustBeGreaterThanOrEqual(options.sessionMarkerAlpha,0), ...
        mustBeLessThanOrEqual(options.sessionMarkerAlpha,1)} = 0.4

    options.summaryLineWidth (1,1) double ...
        {mustBePositive} = 2

end

sessionPaths = sessionPaths(:);
predictorNames = predictorNames(:).';

if isempty(sessionPaths)
    error( ...
        "plotGroupFractionSelectiveByRegion:NoSessions", ...
        "At least one session path must be supplied.");
end

%% Run sessions, skipping sessions with missing or invalid input files

requestedSessionPaths = sessionPaths;
nRequestedSessions = numel(requestedSessionPaths);

sessionResults = cell(nRequestedSessions,1);
sessionSucceeded = false(nRequestedSessions,1);
failureMessages = strings(nRequestedSessions,1);

% Predictor names may need to be inferred from the first successful
% session.
resolvedPredictorNames = predictorNames;

for sessionIndex = 1:nRequestedSessions

    thisSessionPath = requestedSessionPaths(sessionIndex);

    fprintf( ...
        "Processing session %d of %d: %s\n", ...
        sessionIndex, ...
        nRequestedSessions, ...
        thisSessionPath);

    try

        thisResult = getSessionFractionSelectiveByRegion( ...
            thisSessionPath, ...
            resolvedPredictorNames, ...
            minimumDE=options.minimumDE, ...
            fullThresholdPercent=options.fullThresholdPercent, ...
            uniqueThresholdPercent=options.uniqueThresholdPercent, ...
            uniqueFractionThresholdPercent=options.uniqueFractionThresholdPercent, ...
            roiTypeValue=options.roiTypeValue, ...
            validRegionIds=options.validRegionIds);

        % Infer predictor names from the first successful session.
        if isempty(resolvedPredictorNames)
            resolvedPredictorNames = string(thisResult.predictorNames);
        end

        % Ensure all predictor-dependent outputs follow the requested order.
        thisResult = reorderSessionPredictors( ...
            thisResult, ...
            resolvedPredictorNames);

        sessionResults{sessionIndex} = thisResult;
        sessionSucceeded(sessionIndex) = true;

    catch ME

        % Skip expected session-data errors, but do not hide unrelated
        % programming errors.
        isSessionDataError = startsWith( ...
            string(ME.identifier), ...
            "getSessionFractionSelectiveByRegion:");

        if ~isSessionDataError
            rethrow(ME);
        end

        failureMessages(sessionIndex) = string(ME.message);

        warning( ...
            "plotGroupFractionSelectiveByRegion:SkippingSession", ...
            "Skipping session '%s':\n%s", ...
            thisSessionPath, ...
            ME.message);
    end
end

%% Retain successful sessions only

if ~any(sessionSucceeded)
    error( ...
        "plotGroupFractionSelectiveByRegion:NoValidSessions", ...
        "None of the %d supplied sessions could be processed.", ...
        nRequestedSessions);
end

sessionPaths = requestedSessionPaths(sessionSucceeded);
sessionResults = sessionResults(sessionSucceeded);

predictorNames = resolvedPredictorNames;
nPredictors = numel(predictorNames);
nSessions = numel(sessionPaths);

fprintf( ...
    "Successfully processed %d of %d sessions; skipped %d.\n", ...
    nSessions, ...
    nRequestedSessions, ...
    nRequestedSessions-nSessions);

%% define one marker per animal ID

animalIds = strings(nSessions,1);

for sessionIndex = 1:nSessions
    parts = regexp( ...
        char(sessionPaths(sessionIndex)), ...
        '[\\/]+', ...
        'split');
    parts = parts(~cellfun("isempty",parts));
    animalIds(sessionIndex) = string(parts{end-2});
end

[uniqueAnimalIds,~,animalIndex] = unique( ...
    animalIds, ...
    "stable");

markerTypes = [ ...
    "o","s","d","^","v",">","<","p","h","+","x","*"];

animalMarkers = markerTypes(1:numel(uniqueAnimalIds));
sessionMarkers = animalMarkers(animalIndex);

%% Construct union of regions

allRegionIds = zeros(0,1);

for sessionIndex = 1:nSessions
    allRegionIds = [ ...
        allRegionIds; ...
        sessionResults{sessionIndex}.regionIds]; %#ok<AGROW>
end

regionIds = unique(allRegionIds);
nRegions = numel(regionIds);

%% Map Allen region IDs to acronyms

if ~isfile(options.stPath)
    error( ...
        "plotGroupFractionSelectiveByRegion:StructureTreeNotFound", ...
        "Allen structure tree file does not exist: %s", ...
        options.stPath);
end

st = loadStructureTree(options.stPath);

% Adjust these field names if loadStructureTree returns different names.
rid_all = double(st.id);
acr_all = string(st.acronym);

regionLabels = strings(size(regionIds));

for regionIndex = 1:numel(regionIds)

    idx = find(rid_all == regionIds(regionIndex),1);

    if ~isempty(idx)
        regionLabels(regionIndex) = acr_all(idx);
    else
        regionLabels(regionIndex) = string(regionIds(regionIndex));
    end
end

%% Align session results

fractionBySession = nan( ...
    nSessions, ...
    nRegions, ...
    nPredictors);

medianDeUniqueBySession = nan( ...
    nSessions, ...
    nRegions, ...
    nPredictors);

fractionAboveUniqueBySession = nan( ...
    nSessions, ...
    nRegions, ...
    nPredictors);

nValidBySession = zeros( ...
    nSessions, ...
    nRegions, ...
    nPredictors);

nSelectiveBySession = zeros( ...
    nSessions, ...
    nRegions, ...
    nPredictors);

for sessionIndex = 1:nSessions

    thisResult = sessionResults{sessionIndex};

    [isPresent,groupRegionIndex] = ismember( ...
        thisResult.regionIds, ...
        regionIds);

    sourceRows = find(isPresent);
    destinationRows = groupRegionIndex(isPresent);

    for rowIndex = 1:numel(sourceRows)

        sourceRow = sourceRows(rowIndex);
        destinationRow = destinationRows(rowIndex);

        thisFraction = thisResult.fractionSelective(sourceRow,:);
        thisMedianDeUnique = thisResult.medianDeUnique(sourceRow,:);
        thisFractionAboveUnique = thisResult.fractionAboveUniqueThreshold(sourceRow,:);
        thisNValid = thisResult.nValid(sourceRow,:);
        thisNSelective = thisResult.nSelective(sourceRow,:);

        % Exclude unstable region estimates based on very few cells.
        tooFewCells = thisNValid < options.minimumCellsPerRegion;
        thisFraction(tooFewCells) = NaN;
        thisMedianDeUnique(tooFewCells) = NaN;
        thisFractionAboveUnique(tooFewCells) = NaN;

        %store
        fractionBySession( ...
            sessionIndex,destinationRow,:) = ...
            reshape(thisFraction,1,1,nPredictors);

        medianDeUniqueBySession( ...
            sessionIndex,destinationRow,:) = ...
            reshape(thisMedianDeUnique,1,1,nPredictors);

        fractionAboveUniqueBySession( ...
            sessionIndex,destinationRow,:) = ...
            reshape(thisFractionAboveUnique,1,1,nPredictors);

        nValidBySession( ...
            sessionIndex,destinationRow,:) = ...
            reshape(thisNValid,1,1,nPredictors);

        nSelectiveBySession( ...
            sessionIndex,destinationRow,:) = ...
            reshape(thisNSelective,1,1,nPredictors);
    end
end

%% Session-level summary statistics

meanFraction = reshape( ...
    mean(fractionBySession,1,"omitnan"), ...
    nRegions, ...
    nPredictors);

semFraction = reshape( ...
    std(fractionBySession,0,1,"omitnan")./sqrt(nSessions), ...
    nRegions, ...
    nPredictors);

nContributingSessions = reshape( ...
    sum(isfinite(fractionBySession),1), ...
    nRegions, ...
    nPredictors);

medianOfSessionMedians = reshape( ...
    median(medianDeUniqueBySession,1,"omitnan"), ...
    nRegions, ...
    nPredictors);

q25SessionMedians = reshape( ...
    prctile(medianDeUniqueBySession,25,1), ...
    nRegions, ...
    nPredictors);

q75SessionMedians = reshape( ...
    prctile(medianDeUniqueBySession,75,1), ...
    nRegions, ...
    nPredictors);

nMedianSessions = reshape( ...
    sum(isfinite(medianDeUniqueBySession),1), ...
    nRegions, ...
    nPredictors);

%% Determine regions to plot

% Require the requested minimum number of sessions for at least one
% predictor in a region.
regionSessionCount = max( ...
    nContributingSessions, ...
    [], ...
    2);

plotRegion = ...
    regionSessionCount >= options.minimumSessionsPerRegion;

plotRegionIndices = find(plotRegion);

if isempty(plotRegionIndices)
    error( ...
        "plotGroupFractionSelectiveByRegion:NoRegions", ...
        "No regions satisfy minimumSessionsPerRegion=%d.", ...
        options.minimumSessionsPerRegion);
end

plotRegionIds = regionIds(plotRegionIndices);
plotRegionLabels = regionLabels(plotRegionIndices);

%re-order by preferred order
[plotRegionLabels,regionOrder] = ...
    orderAllenRegionAcronyms(plotRegionLabels);

shortRegionLabels = extractBefore( ...
    plotRegionLabels, ...
    strlength(plotRegionLabels));

plotRegionIndices = plotRegionIndices(regionOrder);
plotRegionIds = plotRegionIds(regionOrder);

nPlotRegions = numel(plotRegionIndices);

%% Assign region colors

switch options.regionColorMode

    case "ccf"

        colorMapFile = fullfile( ...
            options.CCFdir, ...
            "Browsing Functions", ...
            "allen_ccf_colormap_2017.mat");

        if ~isfile(colorMapFile)
            error( ...
                "plotGroupFractionSelectiveByRegion:ColormapNotFound", ...
                "Allen CCF colormap file does not exist: %s", ...
                colorMapFile);
        end

        colorData = load(colorMapFile,"cmap");
        cmap = double(colorData.cmap);

        if max(cmap,[],"all") > 1
            cmap = cmap./255;
        end

        regionColors = nan(nPlotRegions,3);

        for plotRegionIndex = 1:nPlotRegions

            structureIndex = find( ...
                rid_all == plotRegionIds(plotRegionIndex), ...
                1);

            if isempty(structureIndex) || ...
                    structureIndex > size(cmap,1)

                regionColors(plotRegionIndex,:) = ...
                    [0.5 0.5 0.5];

            else

                regionColors(plotRegionIndex,:) = ...
                    cmap(structureIndex,:);
            end
        end

    case "standard"

        regionColors = lines(nPlotRegions);

end


titleText = sprintf( ...
    "Fraction selective by Allen region\ndeUnique > %.1f%%", ...
    options.uniqueThresholdPercent);
if ~isempty(options.fullThresholdPercent)
    if options.fullThresholdPercent>0
        titleText = titleText + sprintf( ...
            " and deFull > %.1f%%", ...
            options.fullThresholdPercent);
    end
end
if ~isempty(options.minimumDE)
    if options.minimumDE>0
        titleText = titleText + sprintf( ...
            ", pop. filtered at deFull >= %.1f%%", ...
            options.minimumDE);
    end
end

[fractionFigure,fractionAxes,fractionBars] = ...
    plotRegionalFractionPanels( ...
    predictorNames, ...
    shortRegionLabels, ...
    regionColors, ...
    100*meanFraction(plotRegionIndices,:), ...
    100*semFraction(plotRegionIndices,:), ...
    100*fractionBySession(:,plotRegionIndices,:), ...
    sessionMarkers, ...
    uniqueAnimalIds, ...
    animalMarkers, ...
    titleText, ...
    options);

[medianFigure,medianAxes] = ...
    plotRegionalMedianPanels( ...
    predictorNames, ...
    shortRegionLabels, ...
    regionColors, ...
    medianOfSessionMedians(plotRegionIndices,:), ...
    q25SessionMedians(plotRegionIndices,:), ...
    q75SessionMedians(plotRegionIndices,:), ...
    medianDeUniqueBySession(:,plotRegionIndices,:), ...
    sessionMarkers, ...
    uniqueAnimalIds, ...
    animalMarkers, ...
    options);

if options.plotFractionAboveUniqueThreshold

    [fractionAboveFigure,fractionAboveAxes] = ...
        plotRegionalFractionPanels( ...
        predictorNames, ...
        shortRegionLabels, ...
        regionColors, ...
        100*meanFractionAboveUnique(plotRegionIndices,:), ...
        100*semFractionAboveUnique(plotRegionIndices,:), ...
        100*fractionAboveUniqueBySession(:,plotRegionIndices,:), ...
        sprintf( ...
        "Cells with deUnique > %.1f%%", ...
        options.uniqueFractionThresholdPercent), ...
        sessionMarkers, ...
        uniqueAnimalIds, ...
        animalMarkers, ...
        options);
end

%% Create long-form summary table

nRegions = numel(regionIds);

[regionIndexGrid,predictorGrid] = ndgrid( ...
    1:nRegions, ...
    1:nPredictors);

regionColumn = regionIds(regionIndexGrid(:));
regionColumn = regionColumn(:);

regionLabelColumn = regionLabels(regionIndexGrid(:));
regionLabelColumn = regionLabelColumn(:);

predictorColumn = predictorNames(predictorGrid(:));
predictorColumn = predictorColumn(:);

meanFractionColumn = meanFraction(:);
semFractionColumn = semFraction(:);
nSessionsColumn = nContributingSessions(:);

summaryTable = table( ...
    regionColumn, ...
    regionLabelColumn, ...
    predictorColumn, ...
    meanFractionColumn, ...
    semFractionColumn, ...
    nSessionsColumn);

summaryTable.Properties.VariableNames = { ...
    'regionId', ...
    'regionAcronym', ...
    'predictorName', ...
    'meanFraction', ...
    'semFraction', ...
    'nSessions'};

%% Return outputs

summary = struct;

summary.requestedSessionPaths = requestedSessionPaths;
summary.sessionPaths = sessionPaths;

summary.skippedSessionPaths = ...
    requestedSessionPaths(~sessionSucceeded);

summary.skippedSessionMessages = ...
    failureMessages(~sessionSucceeded);

summary.nRequestedSessions = nRequestedSessions;
summary.nIncludedSessions = nSessions;
summary.nSkippedSessions = nRequestedSessions-nSessions;

summary.predictorNames = predictorNames;
summary.regionIds = regionIds;
summary.regionLabels = regionLabels;

summary.fractionBySession = fractionBySession;
summary.nValidBySession = nValidBySession;
summary.nSelectiveBySession = nSelectiveBySession;

summary.meanFraction = meanFraction;
summary.semFraction = semFraction;
summary.nSessions = nContributingSessions;

summary.animalIds = animalIds;
summary.uniqueAnimalIds = uniqueAnimalIds;
summary.sessionMarkers = sessionMarkers;
summary.animalMarkers = animalMarkers;

summary.medianDeUniqueBySession = ...
    medianDeUniqueBySession;

summary.medianOfSessionMedians = ...
    medianOfSessionMedians;

summary.q25SessionMedians = ...
    q25SessionMedians;

summary.q75SessionMedians = ...
    q75SessionMedians;

summary.nMedianSessions = ...
    nMedianSessions;

summary.fractionAboveUniqueBySession = ...
    fractionAboveUniqueBySession;

if options.plotFractionAboveUniqueThreshold

    summary.meanFractionAboveUnique = ...
        meanFractionAboveUnique;

    summary.semFractionAboveUnique = ...
        semFractionAboveUnique;

    summary.fractionAboveUniqueFigure = ...
        fractionAboveFigure;

    summary.fractionAboveUniqueAxes = ...
        fractionAboveAxes;
end

summary.fractionFigure = fractionFigure;
summary.fractionAxes = fractionAxes;

summary.medianDeUniqueFigure = medianFigure;
summary.medianDeUniqueAxes = medianAxes;

summary.sessionResults = sessionResults;
summary.table = summaryTable;

end


function [fig,axesHandles] = plotRegionalMedianPanels( ...
    predictorNames, regionLabels, regionColors, ...
    centralValues, q25Values, q75Values, ...
    sessionValues, sessionMarkers, uniqueAnimalIds, animalMarkers, options)
%PLOTREGIONALMEDIANPANELS Plot median session-level deUnique by region.
%
% centralValues, q25Values and q75Values:
%   regions x predictors
%
% sessionValues:
%   sessions x regions x predictors

nPredictors = numel(predictorNames);
nRegions = numel(regionLabels);

yPositions = (1:nRegions).';

figureWidth = max( ...
    options.figurePosition(3), ...
    120*nPredictors);

fig = figure( ...
    "Color","w", ...
    "Position",[ ...
    options.figurePosition(1), ...
    options.figurePosition(2)+options.figurePosition(4)+50, ...
    figureWidth, ...
    options.figurePosition(4)], ...
    "Name","Median unique deviance by Allen region");

layout = tiledlayout( ...
    fig, ...
    1, ...
    nPredictors, ...
    "TileSpacing","compact", ...
    "Padding","compact");

axesHandles = gobjects(nPredictors,1);

allFinite = [ ...
    centralValues(isfinite(centralValues)); ...
    q25Values(isfinite(q25Values)); ...
    q75Values(isfinite(q75Values))];

if isempty(allFinite)
    commonLimits = [-1 1];
else
    lowerLimit = min(allFinite);
    upperLimit = max(allFinite);

    valueRange = upperLimit-lowerLimit;

    if valueRange == 0
        padding = max(abs(upperLimit)*0.1,0.1);
    else
        padding = 0.08*valueRange;
    end

    commonLimits = [ ...
        min(0,lowerLimit-padding), ...
        max(0,upperLimit+padding)];
end

for predictorIndex = 1:nPredictors

    ax = nexttile(layout);
    axesHandles(predictorIndex) = ax;

    hold(ax,"on");

    %% Session-level regional medians, with marker type indicating animal

    for regionIndex = 1:nRegions

        values = sessionValues( ...
            :,regionIndex,predictorIndex);

        values = values(:);
        validSession = isfinite(values);

        if ~any(validSession)
            continue
        end

        validValues = values(validSession);
        validMarkers = sessionMarkers(validSession);

        nValues = numel(validValues);

        if nValues == 1
            yOffset = 0;
        else
            yOffset = linspace(-0.12,0.12,nValues).';
        end

        for valueIndex = 1:nValues

            thisMarker = validMarkers(valueIndex);

            scatter( ...
                ax, ...
                validValues(valueIndex), ...
                regionIndex+yOffset(valueIndex), ...
                options.sessionMarkerSize, ...
                "k", ...
                "Marker",thisMarker, ...
                "MarkerFaceColor",markerFaceColor(thisMarker), ...
                "MarkerEdgeColor","k", ...
                "MarkerFaceAlpha",options.sessionMarkerAlpha, ...
                "MarkerEdgeAlpha",options.sessionMarkerAlpha, ...
                "HandleVisibility","off");
        end
    end

    %% IQR and median of session medians

    for regionIndex = 1:nRegions

        medianValue = ...
            centralValues(regionIndex,predictorIndex);

        q25 = q25Values(regionIndex,predictorIndex);
        q75 = q75Values(regionIndex,predictorIndex);

        if ~isfinite(medianValue)
            continue
        end

        thisColor = regionColors(regionIndex,:);

        if isfinite(q25) && isfinite(q75)

            plot( ...
                ax, ...
                [q25,q75], ...
                [regionIndex,regionIndex], ...
                "-", ...
                "Color",thisColor, ...
                "LineWidth",options.summaryLineWidth, ...
                "HandleVisibility","off");
        end

        scatter( ...
            ax, ...
            medianValue, ...
            regionIndex, ...
            35, ...
            "Marker","o", ...
            "MarkerFaceColor","w", ...
            "MarkerEdgeColor",thisColor, ...
            "LineWidth",options.summaryLineWidth, ...
            "HandleVisibility","off");
    end

    xline( ...
        ax, ...
        0, ...
        "Color",[0.5 0.5 0.5], ...
        "LineStyle",":", ...
        "HandleVisibility","off");

    ylim(ax,[0.4,nRegions+0.6]);
    yticks(ax,yPositions);
    yticklabels(ax,strings(nRegions,1));

    if predictorIndex == 1

        currentLimits = commonLimits;
        labelX = currentLimits(1)-0.04*diff(currentLimits);

        for regionIndex = 1:nRegions
            text( ...
                ax, ...
                labelX, ...
                regionIndex, ...
                regionLabels(regionIndex), ...
                "HorizontalAlignment","right", ...
                "VerticalAlignment","middle", ...
                "Interpreter","none", ...
                "Clipping","off");
        end
    end

    xlim(ax,commonLimits);

    title( ...
        ax, ...
        replace(predictorNames(predictorIndex),"_"," "), ...
        "Interpreter","none");

    box(ax,"off");
    ax.XGrid = "on";
    ax.YGrid = "off";
    ax.GridAlpha = 0.15;
    ax.Layer = "top";
end

linkaxes(axesHandles,"xy");

set( ...
    axesHandles, ...
    "XLim",commonLimits, ...
    "XLimMode","manual", ...
    "YLim",[0.4,nRegions+0.6], ...
    "YLimMode","manual");

xlabel( ...
    layout, ...
    "Median unique c.v. deviance explained (%)");

title( ...
    layout, ...
    "Regional median deUnique: median and IQR across sessions", ...
    "Interpreter","none");

end

function [fig,axesHandles,barHandles] = ...
    plotRegionalFractionPanels( ...
    predictorNames, regionLabels, regionColors, ...
    meanPercent, semPercent, sessionPercent, ...
    sessionMarkers, uniqueAnimalIds, animalMarkers, ...
    titleText, options)
%PLOTREGIONALFRACTIONPANELS Horizontal regional fraction panels.

nPredictors = numel(predictorNames);
nRegions = numel(regionLabels);

yPositions = (1:nRegions).';

upperValues = meanPercent+semPercent;

commonXLimit = max( ...
    upperValues, ...
    [], ...
    "all", ...
    "omitnan");

if isempty(commonXLimit) || ~isfinite(commonXLimit)
    commonXLimit = 5;
end

commonXLimit = min(100,max(5,1.1*commonXLimit));

figureWidth = max( ...
    options.figurePosition(3), ...
    120*nPredictors);

fig = figure( ...
    "Color","w", ...
    "Position",[ ...
    options.figurePosition(1), ...
    options.figurePosition(2), ...
    figureWidth, ...
    options.figurePosition(4)], ...
    "Name",titleText);

layout = tiledlayout( ...
    fig, ...
    1, ...
    nPredictors, ...
    "TileSpacing","compact", ...
    "Padding","compact");

axesHandles = gobjects(nPredictors,1);
barHandles = cell(nPredictors,1);

for predictorIndex = 1:nPredictors

    ax = nexttile(layout);
    axesHandles(predictorIndex) = ax;

    hold(ax,"on");

    predictorMean = meanPercent(:,predictorIndex);
    predictorSEM = semPercent(:,predictorIndex);

    thisBars = gobjects(nRegions,1);

    %% Filled bars

    for regionIndex = 1:nRegions

        if ~isfinite(predictorMean(regionIndex))
            continue
        end

        thisBars(regionIndex) = barh( ...
            ax, ...
            yPositions(regionIndex), ...
            predictorMean(regionIndex), ...
            0.75, ...
            "FaceColor",regionColors(regionIndex,:), ...
            "EdgeColor",regionColors(regionIndex,:), ...
            "FaceAlpha",1,...
            "LineWidth",options.summaryLineWidth, ...
            "HandleVisibility","off");
    end

    barHandles{predictorIndex} = thisBars;

    %% Colored SEM, without caps

    for regionIndex = 1:nRegions

        if ~isfinite(predictorMean(regionIndex)) || ...
                ~isfinite(predictorSEM(regionIndex))
            continue
        end

        errorbar( ...
            ax, ...
            predictorMean(regionIndex), ...
            yPositions(regionIndex), ...
            predictorSEM(regionIndex), ...
            predictorSEM(regionIndex), ...
            "horizontal", ...
            "LineStyle","none", ...
            "Color",'k',...%regionColors(regionIndex,:), ...
            "LineWidth",1.5, ...
            "CapSize",0, ...
            "HandleVisibility","off");
    end

    %% Individual session percentages, with marker type indicating animal

    for regionIndex = 1:nRegions

        values = sessionPercent( ...
            :,regionIndex,predictorIndex);

        values = values(:);
        validSession = isfinite(values);

        if ~any(validSession)
            continue
        end

        validValues = values(validSession);
        validMarkers = sessionMarkers(validSession);

        nValues = numel(validValues);

        if nValues == 1
            yOffset = 0;
        else
            yOffset = linspace(-0.12,0.12,nValues).';
        end

        for valueIndex = 1:nValues

            thisMarker = validMarkers(valueIndex);

            scatter( ...
                ax, ...
                validValues(valueIndex), ...
                regionIndex+yOffset(valueIndex), ...
                options.sessionMarkerSize, ...
                "k", ...
                "Marker",thisMarker, ...
                "MarkerFaceColor",markerFaceColor(thisMarker), ...
                "MarkerEdgeColor","k", ...
                "MarkerFaceAlpha",options.sessionMarkerAlpha, ...
                "MarkerEdgeAlpha",options.sessionMarkerAlpha, ...
                "HandleVisibility","off");
        end
    end

    ylim(ax,[0.4,nRegions+0.6]);
    yticks(ax,yPositions);
    yticklabels(ax,strings(nRegions,1));

    if predictorIndex == 1

        labelX = -0.04*commonXLimit;

        for regionIndex = 1:nRegions
            text( ...
                ax, ...
                labelX, ...
                regionIndex, ...
                regionLabels(regionIndex), ...
                "HorizontalAlignment","right", ...
                "VerticalAlignment","middle", ...
                "Interpreter","none", ...
                "Clipping","off");
        end
    end

    xlim(ax,[0,commonXLimit]);

    title( ...
        ax, ...
        replace(predictorNames(predictorIndex),"_"," "), ...
        "Interpreter","none");

    box(ax,"off");
    ax.XGrid = "on";
    ax.YGrid = "off";
    ax.GridAlpha = 0.15;
    ax.Layer = "top";
end

linkaxes(axesHandles,"xy");

set( ...
    axesHandles, ...
    "XLim",[0,commonXLimit], ...
    "XLimMode","manual", ...
    "YLim",[0.4,nRegions+0.6], ...
    "YLimMode","manual");

xlabel(layout,"Cells (%)");

title( ...
    layout, ...
    titleText, ...
    "Interpreter","none");

end

function result = reorderSessionPredictors(result,requestedNames)
%REORDERSESSIONPREDICTORS Align result columns to requested predictor order.

requestedNames = string(requestedNames(:).');
returnedNames = string(result.predictorNames(:).');

[isPresent,columnOrder] = ismember( ...
    requestedNames, ...
    returnedNames);

if any(~isPresent)
    error( ...
        "plotFeatureSelectiveByRegion:MissingPredictors", ...
        "Session result is missing predictor(s): %s", ...
        strjoin(requestedNames(~isPresent),", "));
end

predictorFields = [ ...
    "fractionSelective", ...
    "medianDeUnique", ...
    "q25DeUnique", ...
    "q75DeUnique", ...
    "fractionAboveUniqueThreshold", ...
    "nAboveUniqueThreshold", ...
    "nValid", ...
    "nSelective"];

for fieldIndex = 1:numel(predictorFields)

    fieldName = predictorFields(fieldIndex);

    if ~isfield(result,fieldName)
        continue
    end

    values = result.(fieldName);

    if size(values,2) ~= numel(returnedNames)
        error( ...
            "plotFeatureSelectiveByRegion:PredictorDimensionMismatch", ...
            ["Field '%s' has %d columns, but the session result " ...
             "contains %d predictor names."], ...
            fieldName, ...
            size(values,2), ...
            numel(returnedNames));
    end

    result.(fieldName) = values(:,columnOrder);
end

result.predictorNames = requestedNames;

end

function faceColor = markerFaceColor(markerType)
%MARKERFACECOLOR Fill closed markers and leave line markers unfilled.

if ismember(markerType,["+","x","*","."])
    faceColor = "none";
else
    faceColor = "k";
end

end