function params_all = defaultParams()
% Generates default parameters for PETH output and tuning statistics.

params_all = struct( ...
    'activity_type',     'deconv', ...
    'trialTypeField',    {'contrastDiff','stimSide','choice','feedbackType','probabilityLeft'}, ...
    'trialTypeVals',     { ...
        [-1,-.5,-.25,-.125,-.0625,0,.0625,.125,.25,.5,1], ...
        [-1,1], ...
        [-1,1], ...
        [-1,1], ...
        [0.2,0.5,0.8]}, ...
    'compareVals',       { ...
        [-1,1], ...
        [-1,1], ...
        [-1,1], ...
        [-1,1], ...
        [0.2,0.8]}, ...
    'trialTypeFilter',   {'', 'contrastDiff~=0', '', 'contrastDiff~=0', ''}, ...
    'condFields',        {{'choice'}, {'choice'}, {'stimSide'}, {'choice'}, {'stimSide'}}, ...
    'evnt',              {'stimOn','stimOn','choiceMovement','feedback','stimOn'}, ...
    'twin_all',          {[-1,3],[-1,3],[-2.5,1.5],[-1.5,2.5],[-2,2]}, ...
    'twin_bl',           'none', ...
    'twin_ev',           {[0,0.4],[0,0.4],[-0.2,0.2],[0,0.4],[-0.5,-0.1]}, ...
    'nTrialsMin',        50, ...
    'nTrialsToKeep',     false, ...
    'minTrialsPerCond',  10, ...
    'minTrialsPerCombo', 2, ...
    'stat_to_use',       'ccu', ...
    'statCV',            '', ...
    'pthresh',           0.05, ...
    'nPseudoSessions',   199);

%old
% params_all = struct( ...
%     'activity_type',   'deconv', ...
%     'trialTypeField',  {'contrastDiff','choice','feedbackType','probabilityLeft'}, ...
%     'trialTypeVals',   {[-1,-.5,-.25,-.125,-.0625,0,.0625,.125,.25,.5,1], [-1,1], [-1,1], [0.2,0.8]}, ...
%     'trialTypeFilter', {'contrastDiff~=0', '', 'contrastDiff~=0', ''}, ...
%     'condFields',      {{'choice'},{'contrastDiff'},{'choice'},{'contrastDiff'}}, ...
%     'evnt',            {'stimOn','choiceMovement','feedback','stimOn'}, ...
%     'twin_all',        {[-1,3],[-2.5,1.5],[-1.5,2.5],[-2,2]}, ...
%     'twin_bl',         'none', ...
%     'twin_ev',         {[0,0.4],[-0.2,0.2],[0,0.4],[-0.5,-0.1]}, ...
%     'nTrialsMin',      50, ...
%     'nTrialsToKeep',   false, ...
%     'minTrialsPerCond',10, ...
%     'minTrialsPerCombo',2, ...
%     'stat_to_use',     'ccu', ...
%     'nComp',           1, ...
%     'statCV',          'even', ...
%     'pthresh',         0.05, ...
%     'nPseudoSessions', 199);
end