function passTable = threshold_neuralQMs(neuralQMs, thresholds)
% Threshold neural quality metrics.
%
% INPUT
% neuralQMs  : 1 x nROIs struct containing neural quality metrics
% thresholds : optional threshold struct. If omitted, uses defaults from
%              get_neuralQMThresholds
%
% OUTPUT
% passTable  : nROIs x nMetrics logical table; true = metric passed

if nargin < 2 || isempty(thresholds)
    thresholds = get_neuralQMThresholds();
end

% Convert struct array to vectors
noiseLevel         = [neuralQMs.noiseLevel]';
meanVal            = [neuralQMs.mean]';
stdVal             = [neuralQMs.std]';
skewVal            = [neuralQMs.skew]';
varVal             = [neuralQMs.var]';
snrVar             = [neuralQMs.snrVar]';
snrTransient       = [neuralQMs.snrTransient]';
residualNeuropilR2 = [neuralQMs.residualNeuropilR2]';
saturationRatio    = [neuralQMs.saturationRatio]';
upperRebound       = [neuralQMs.upperRebound]';

% Apply thresholds
passTable = table( ...
    noiseLevel         <  thresholds.noiseLevel, ...
    meanVal            >  thresholds.mean, ...
    stdVal             >= thresholds.std, ...
    skewVal            >  thresholds.skew, ...
    varVal             >  thresholds.var, ...
    snrVar             >  thresholds.snrVar, ...
    snrTransient       >  thresholds.snrTransient, ...
    residualNeuropilR2 <= thresholds.residualNeuropilR2, ...
    saturationRatio    <  thresholds.saturationRatio, ...
    upperRebound       <  thresholds.upperRebound, ...
    'VariableNames', { ...
        'noiseLevel', ...
        'mean', ...
        'std', ...
        'skew', ...
        'var', ...
        'snrVar', ...
        'snrTransient', ...
        'residualNeuropilR2', ...
        'saturationRatio', ...
        'upperRebound'});

end